  
var paeiouIcons = [
	"bug_bomber",
	"bug_fighter",
	"bug_radar",
	"bug_radar_adv",
	"hydra",
	"bombardier",
	"bug_sniper",
	"bug_boomer_egg",
	"bug_adv_boomer_egg",
	"boomer",
	"adv_boomer",
	"bug_aa",
	"bug_adv_aa",
	"manticore",
	"bug_evo_chamber",
	"ripper",
	"ripper_stealth",
	"bug_titan",
	"small_egg",
	"medium_egg",
	"small_turret",
	"big_runner",
	"runner",
	"asteroid",
	"basic_hive",
	"medium_hive",
	"advanced_hive",
    "blank_blip",
	"big_grunt",
	"grunt",
	"spitter",
	"warrior",
	"bug_zapper",
	"big_warrior",
	"basilisk",
	"scorcher"
	

];
model.strategicIcons(model.strategicIcons().concat(paeiouIcons));